config/routes.rb
Rails.application.routes.draw do
  resources :time_banks
  resources :taggings
  resources :comments
  resources :videos
  resources :feeds
  resources :wants_attachments
  resources :have_attachments
  resources :pics
  resources :friendships do
    member do
      post :friendships
    end
  end
  resources :trackings
  resources :area
  resources :notes, only: [:new, :create, :show]
  resources :questions, only: [:new, :create, :show] do
    resources :answers, only: [:create]
  end
  resources :debates, only: [:index, :new, :create, :show] do
    resources :arguments
  end
  post 'area/create'
  post 'area/edit'
  get 'area/:id' => 'area#solo_pic'

  get 'area/:id/new_layer' => 'area#new_layer'
  post 'area/:id/create_layer' => 'area#create_layer'

  get 'posts/new_des' => 'posts#new_design'

  get 'posts/homepage' => 'posts#homepage'
  get 'posts/messages' => 'posts#messages'

  post 'profiles/update_pic' => 'profiles#update_pic'

  get '/profile_posts' => 'profiles#profile_posts'
  get 'have/:id' => 'haves#profile_have', as: :profile_have
  get 'want/:id' => 'wants#profile_want', as: :profile_want
  get '/profile_tags' => 'profiles#profile_tag'

  get '/chat' => 'profiles#chat'

  get '/public_feed' => 'posts#public_feed'

  get 'pic/:id' => 'pics#solo_pic', as: :solo_pic

  get 'video/:id' => 'videos#show_video', as: :show_video

  get '/show_have' => 'haves#show_have'

  get '/show_want' => 'wants#show_want'

  resources :rooms
  resources :messages

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  resources :haves

  resources :wants

  resources :posts do
    member do
      get :new_layer
      post :create_layer
      post :create_token
      get :all_tokens
      get :show_token
      post :add_rating
      resources :tokens do
        resources :comments do
          get 'add_vote', on: :collection
        end
      end
    end
  end

  root to: 'posts#homepage'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :admin do
    resources :users
  end

  resources :users do
    member do

      resources :items do
        get :items, on: :member
      end
      post :profile_update, to: 'profiles#update'
      get :profile_edit, to: 'profiles#edit'
    end
  end

  # form_for is easier to use with a resourceful route
  resources :contact_forms, only: [:create]
  resources :profiles
  get 'contact' => 'contact_forms#new', as: 'contact'
  post '/users/edit' => 'users/registrations#update'
  # post '/update_user' => 'users/registrations#update'
end

app/models/want.rb
class Want < ApplicationRecord
  has_many :wants_attachments
  accepts_nested_attributes_for :wants_attachments

  belongs_to :user
end

app/controllers/wants_controller.rb
class WantsController < ApplicationController
  layout 'profiles'

  before_action :set_want, only: [:edit, :update, :index]
  before_action :set_user, only: [:show, :index]

  after_action :authorize_want, only: [ :index, :show, :update, :edit, :new, :create, :destroy, :profile_want]

  def index
    policy_scope(Have) if current_user

    @want = Want.where(user_id: current_user.id)
  end

  def show
    policy_scope(Have) if current_user

    @want = Want.where(:user_id => params[:id])
  end

  def profile_want
    @want = Want.find(params[:id])

    @disable_sidebar = true

    @wants_attachment = @want.wants_attachments.all
  end

  def new
    @want = Want.new

    @disable_sidebar = true

    @wants_attachment = @want.wants_attachments.build
  end

  def create
    @want = Want.new(params.required(:want).permit(:user_id, :title, :description, :price, wants_attachments_attributes: [:id, :want_id, :image]))

    @want.user_id = current_user.id

    if @want.save
      params[:wants_attachments]['image'].each do |a|
        @wants_attachment = @want.wants_attachments.create!(:image => a)
      end
      redirect_to want_path(current_user.id)
    else
      render :new
    end
  end

  def edit
    @disable_sidebar = true
  end

  def update
    if @want.update(params.required(:want).permit(:user_id, :title, :description, :price, wants_attachments_attributes: [:id, :want_id, :image]))
      redirect_to profile_want_path(@want)
    else
      render :edit
    end
  end

  def destroy
    @want = Want.find(params[:id])
    @want.destroy

    @want.delete
    redirect_to want_path(current_user.id), notice: "Your post was deleted successfully"
  end

  private

  def authorize_want
    authorize Want
  end

  def set_want
    @want = Want.find(params[:id])
  end

  def set_user
    @user = User.friendly.find(params[:id])
  end

end

app/views/wants/edit.html.erb
<div class="container-fluid">
  <div class="row form-header">
    <h2>
      Edit Wanted Skill
    </h2>
  </div>
  <div class="row form-body">
    <%= render "wants/partials/form" %>
  </div>
</div>

app/views/wants/index.html.erb
<div class="container-flex">
  <div class="row show-header">
    <h1>
      Want
    </h1>
  </div>
  <div class="col-md-12">
    <div class="row table col-md-12">
      <table data-toggle="table">
        <thead class="table-header">
        <tr>
          <th class="col-md-3 text-center table-head-label">Skill</th>
          <th class="col-md-6 text-center table-head-label">Description</th>
          <th class="col-md-2 text-center table-head-label">Price</th>
        </tr>
        </thead>
        <% @want.each do |f| %>
          <tbody>
          <tr class="text-center">
            <td class="table-body-box"><%= link_to f.title, want_path(f), class: "want-box" %></td>
            <td class="table-body-box"><%= link_to truncate(f.description, length: 150), want_path(f), class: "want-box" %></td>
            <td class="table-body-box"><%= link_to f.price, want_path(f), class: "want-box" %></td>
          </tr><% end %>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row have-link-box col-md-offset-1">
    <h3 class="have-links">
      <%= link_to "Add New", new_want_path, :class => "b5" %>
    </h3>
  </div>
</div>
</div>

app/views/wants/new.html.erb
<div class="container-fluid">
  <div class="row post-header">
    <h2>
      New Skill Wanted
    </h2>
  </div>
  <div class="row form-body">
    <%= render "wants/partials/form" %>
  </div>
</div>

app/views/wants/profile_want.html.erb
<div class="container-fluid">
  <div class="col-md-12 notes-box">
    <div class="row show-header-b text-center">
      <h1>
        <%= @want.title %>
      </h1>
    </div>
    <div class="row show-box-b">
      <div class="col-md-4">
        <p><b>Price: <%= @want.price %></b></p>
      </div>
      <div class="col-md-2 col-md-offset-6">
        <p><b><%= @want.user.first_name %> <%= @want.user.last_name %></b></p>
      </div>
    </div>
    <div class="row show-box">
      <%= @want.description %>
    </div>
    <div class="row show-box">
      <% @want.wants_attachments.each do |f| %>
        <%= image_tag(f.image, {:style => "max-width: 40%", :class => "profile-pic text-center"}) %>
      <% end %>
    </div>
    <div class="row box-link-row">
      <div class="box-links-2 col-md-1">
        <%= link_to "Back", want_path(@want.user_id), class: "b2" %>
      </div>
      <div class="box-links-2 col-md-1">
        <% if current_user.id == @want.user_id %>
          <%= link_to "Edit", edit_want_path(@want), class: "b2" %>
        <% end %>
      </div>
      <div class="box-links-2 col-md-1">
        <% if current_user.id == @want.user_id %>
          <%= link_to 'Destroy', want_path(@want),
                      method: :delete, data: { confirm: 'Are you sure?' }, class: "b2" %>
        <% end %>
      </div>
      <div class="box-links-2 col-md-4 col-md-offset-5 text-right">
        <b><span><i class="glyphicon glyphicon-calendar glyph-padding"></i> <%= @want.created_at.strftime("%I:%M %p, %m/%d/%Y") %> </span></b>
      </div>
    </div>
  </div>
</div>

app/views/wants/show.html.erb
<div class="container-fluid">
  <div class="row show-header">
    <h1>
      Want
    </h1>
  </div>
  <div class="row">
    <div class="col-md-12">
      <table class="table table-striped table-hover table-sm">
        <thead>
        <tr>
          <th>
            Skill
          </th>
          <th>
            Description
          </th>
          <th>
            Price
          </th>
        </tr>
        </thead>
        <% @want.each do |f| %>
        <tbody>

        <tr class="table-active">
          <td>
            <%= link_to f.title, profile_want_path(f), class: "want-box" %>
          </td>
          <td>
            <%= link_to truncate(f.description, length: 150), profile_want_path(f), class: "want-box" %>
          </td>
          <td>
            <%= link_to f.price, profile_want_path(f), class: "want-box" %>
          </td>
        </tr>
        </tbody>
          <% end %>
      </table>
    </div>
  </div>
  <div class="row have-link-box col-md-offset-1">
    <h3 class="have-links">
      <% if @user.id == current_user.id %>
        <%= link_to "Add New", new_want_path, :class => "b5" %>
      <% end %>
    </h3>
  </div>
</div>

app/views/wants/show_want.html.erb
<div class="container-fluid">
  <div class="col-md-12 notes-box">
    <div class="row show-header-b text-center">
      <h1>
        <%= @want.title %>
      </h1>
    </div>
    <div class="row show-box">
      <%= @want.description %>
    </div>
    <div class="row show-box">
      <% @want.wants_attachments.each do |f| %>
        <%= image_tag(f.image, {:style => "max-width: 40%", :class => "profile-pic text-center"}) %>
      <% end %>
    </div>
    <div class="row box-link-row">
      <div class="box-links-2 col-md-1">
        <%= @want.price %>
      </div>
      <div class="box-links-2 col-md-1">
        <% if user_signed_in? %>
          <% if current_user.id == @want.user_id %>
            <%= link_to "Edit", edit_want_path(@want), class: "b2" %>
          <% end %>
        <% else %>
          <p><b><%= @want.user.first_name %> <%= @want.user.last_name %></b></p>
        <% end %>
      </div>
      <div class="box-links-2 col-md-1">
        <% if user_signed_in? %>
          <% if current_user.id == @want.user_id %>
            <%= link_to 'Destroy', want_path(@want),
                        method: :delete, data: { confirm: 'Are you sure?' }, class: "b2" %>
          <% end %>
        <% end %>
      </div>
      <div class="box-links-2 col-md-4 col-md-offset-5 text-right">
        <b><span><i class="glyphicon glyphicon-calendar glyph-padding"></i> <%= @want.created_at.strftime("%I:%M %p, %m/%d/%Y") %> </span></b>
      </div>
    </div>
  </div>
</div>