config/routes.rb
Rails.application.routes.draw do
  resources :time_banks
  resources :taggings
  resources :comments
  resources :videos
  resources :feeds
  resources :wants_attachments
  resources :have_attachments
  resources :pics
  resources :friendships do
    member do
      post :friendships
    end
  end
  resources :trackings
  resources :area
  resources :notes, only: [:new, :create, :show]
  resources :questions, only: [:new, :create, :show] do
    resources :answers, only: [:create]
  end
  resources :debates, only: [:index, :new, :create, :show] do
    resources :arguments
  end
  post 'area/create'
  post 'area/edit'
  get 'area/:id' => 'area#solo_pic'

  get 'area/:id/new_layer' => 'area#new_layer'
  post 'area/:id/create_layer' => 'area#create_layer'

  get 'posts/new_des' => 'posts#new_design'

  get 'posts/homepage' => 'posts#homepage'
  get 'posts/messages' => 'posts#messages'

  post 'profiles/update_pic' => 'profiles#update_pic'

  get '/profile_posts' => 'profiles#profile_posts'
  get 'have/:id' => 'haves#profile_have', as: :profile_have
  get 'want/:id' => 'wants#profile_want', as: :profile_want
  get '/profile_tags' => 'profiles#profile_tag'

  get '/chat' => 'profiles#chat'

  get '/public_feed' => 'posts#public_feed'

  get 'pic/:id' => 'pics#solo_pic', as: :solo_pic

  get 'video/:id' => 'videos#show_video', as: :show_video

  get '/show_have' => 'haves#show_have'

  get '/show_want' => 'wants#show_want'

  resources :rooms
  resources :messages

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  resources :haves

  resources :wants

  resources :posts do
    member do
      get :new_layer
      post :create_layer
      post :create_token
      get :all_tokens
      get :show_token
      post :add_rating
      resources :tokens do
        resources :comments do
          get 'add_vote', on: :collection
        end
      end
    end
  end

  root to: 'posts#homepage'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :admin do
    resources :users
  end

  resources :users do
    member do

      resources :items do
        get :items, on: :member
      end
      post :profile_update, to: 'profiles#update'
      get :profile_edit, to: 'profiles#edit'
    end
  end

  # form_for is easier to use with a resourceful route
  resources :contact_forms, only: [:create]
  resources :profiles
  get 'contact' => 'contact_forms#new', as: 'contact'
  post '/users/edit' => 'users/registrations#update'
  # post '/update_user' => 'users/registrations#update'
end

app/models/video.rb
class Video < ApplicationRecord
  belongs_to :user

end

app/controllers/videos_controller.rb
class VideosController < ApplicationController
  layout 'profiles'

  before_action :set_video, only: [:edit, :update, :index]
  before_action :set_user, only: [:show, :index]

  after_action :authorize_video, only: [:index, :show, :create, :update, :edit, :new, :destroy, :show_video]

  def index
    policy_scope(Video) if current_user

    @video = Video.all.sort_by{|e| e["created_at DESC"]}
  end

  def show_video
    @disable_sidebar = true

    @video = Video.find(params[:id])
  end

  def show
    policy_scope(Video) if current_user

    @video = Video.where(:user_id => params[:id])
  end

  def new
    @disable_sidebar = true

    @video = Video.new
  end

  def create
    @video = Video.create(params.require(:video).permit(:title, :video, :description, :user_id))

    @video.user_id = current_user.id

    if @video.save!
      redirect_to video_path(current_user.id)
    else
      render :new
    end
  end

  def edit
    @disable_sidebar = true
  end

  def update
    if @video.update(params.required(:video).permit(:name, :video, :description, :user_id))
      redirect_to show_video_path(@video)
    else
      render :edit
    end
  end

  def destroy
    @video = Video.find(params[:id])
    @video.destroy

    @video.delete
    redirect_to video_path(@video.user_id), notice: "Your video was deleted successfully"
  end

  private

  def authorize_video
    authorize Video
  end

  def set_video
    @video = Video.find(params[:id])
  end

  def set_user
    @user = User.friendly.find(params[:id])
  end
end

app/helpers/videos_helper.rb
module VideosHelper
end

app/views/videos/_form.html.erb
<%= bootstrap_form_for @video, class: "form-horizonatl" do |f| %>
  <div class="row form-cont">
    <div class="col-md-10">
      <%= f.text_field :title %>
      <%= f.text_area :description, class: "tinymce", rows: 10 , cols: 90  %>
      <%= f.text_field :video, prepend: 'https://www.youtube.com/watch?v=' %>

      <%= f.submit 'Submit', class: 'b4' %>
    </div>
  </div>
<% end %>

app/views/videos/edit.html.erb
<div class="container-flex">
  <div class="row post-header">
    <h2>
      Edit Video
    </h2>
  </div>
  <div class="row form-body">
    <%= render "videos/form" %>
  </div>
</div>

app/views/videos/index.html.erb
<div class="container-fluid">
  <div class="col-md-12 notes-box">
    <div class="row post-header-b">
      <div class="col-md-10">
        <h1>
          My Videos
        </h1>
      </div>
      <div class="col-md-2">
        <%= link_to "new video", new_video_path, class: "b7" %>
      </div>
    </div>
    <div>
      <% @video.in_groups_of(2, false).each do |group| %>
        <div class='row'>
          <% group.each do |p| %>
            <div class='col-md-5 note-box'>
              <% if p.user_id == current_user.id %>
                <h3 class="text-center">
                  <%= link_to p.title, video_path(p), class: "pic-link" %>
                </h3>
                <p class="text-center">
                  <%= truncate(p.description, length: 50) %>
                </p>
                <p class="text-center">
                  <iframe width="420" height="315"
                   src="https://www.youtube.com/embed/<%= p.video %>">
                  </iframe>
                </p>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/videos/new.html.erb
<div class="container-flex">
  <div class="row post-header">
    <h2>
      New Video
    </h2>
  </div>
  <div class="row form-body">
    <%= render "videos/form" %>
  </div>
</div>

app/views/videos/show.html.erb
<div class="container-fluid">
  <div class="col-md-12 notes-box">
    <div class="row post-header-b">
      <div class="col-md-10">
        <h1>
          <%= @user.first_name %>'s Videos
        </h1>
      </div>
      <div class="col-md-2">
        <% if @user.id == current_user.id %>
          <%= link_to "new video", new_video_path, class: "b7" %>
        <% end %>
      </div>
    </div>
    <div>
      <% @video.in_groups_of(2, false).each do |group| %>
        <div class='row'>
          <% group.each do |p| %>
            <div class='col-md-5 note-box'>
              <% if p.user_id == current_user.id %>
                <h3 class="text-center">
                  <%= link_to p.title, show_video_path(p), class: "pic-link" %>
                </h3>
                <p class="text-center">
                  <%= truncate(p.description, length: 50) %>
                </p>
                <p class="text-center">
                  <iframe width="420" height="315"
                          src="https://www.youtube.com/embed/<%= p.video %>">
                  </iframe>
                </p>
              <% end %>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/videos/show_video.html.erb
<div class="container-fluid">
  <div class="col-md-12 notes-box">
    <div class="row show-header text-center">
      <h1><b>
        <%= @video.title %>
      </b></h1>
    </div>
    <div class="row text-center">
      <p><%= @video.description %></p>
    </div>
    <div class="row show-box">
      <div class="col-md-12 text-center">
        <iframe width="840" height="630"
                src="https://www.youtube.com/embed/<%= @video.video %>">
        </iframe>
      </div>
    </div>
    <div class="row box-link-row">
      <div class="box-links-2 col-md-1">
        <%= link_to "Back", video_path(@video.user_id), class: "b2" %>
      </div>
      <div class="box-links-2 col-md-1">
        <% if user_signed_in? %>
          <% if current_user.id == @video.user_id %>
            <%= link_to "Edit", edit_video_path(@video), class: "b2" %>
          <% end %>
        <% else %>
          <p><b><%= @video.user.first_name %> <%= @video.user.last_name %></b></p>
        <% end %>
      </div>
      <div class="box-links-2 col-md-2">
        <% if user_signed_in? %>
          <% if current_user.id == @video.user_id %>
            <%= link_to 'Destroy', video_path(@video),
                        method: :delete, data: { confirm: 'Are you sure?' }, class: "b2" %>
          <% end %>
        <% end %>
      </div>
      <div class="box-links-2 col-md-3 col-md-offset-5 text-right">
        <b><span><i class="glyphicon glyphicon-calendar glyph-padding"></i> <%= @video.created_at.strftime("%I:%M %p, %m/%d/%Y") %> </span></b>
      </div>
    </div>
  </div>

</div>