config/routes.rb
Rails.application.routes.draw do
  resources :time_banks
  resources :taggings
  resources :comments
  resources :videos
  resources :feeds
  resources :wants_attachments
  resources :have_attachments
  resources :pics
  resources :friendships do
    member do
      post :friendships
    end
  end
  resources :trackings
  resources :area
  resources :notes, only: [:new, :create, :show]
  resources :questions, only: [:new, :create, :show] do
    resources :answers, only: [:create]
  end
  resources :debates, only: [:index, :new, :create, :show] do
    resources :arguments
  end
  post 'area/create'
  post 'area/edit'
  get 'area/:id' => 'area#solo_pic'

  get 'area/:id/new_layer' => 'area#new_layer'
  post 'area/:id/create_layer' => 'area#create_layer'

  get 'posts/new_des' => 'posts#new_design'

  get 'posts/homepage' => 'posts#homepage'
  get 'posts/messages' => 'posts#messages'

  post 'profiles/update_pic' => 'profiles#update_pic'

  get '/profile_posts' => 'profiles#profile_posts'
  get 'have/:id' => 'haves#profile_have', as: :profile_have
  get 'want/:id' => 'wants#profile_want', as: :profile_want
  get '/profile_tags' => 'profiles#profile_tag'

  get '/chat' => 'profiles#chat'

  get '/public_feed' => 'posts#public_feed'

  get 'pic/:id' => 'pics#solo_pic', as: :solo_pic

  get 'video/:id' => 'videos#show_video', as: :show_video

  get '/show_have' => 'haves#show_have'

  get '/show_want' => 'wants#show_want'

  resources :rooms
  resources :messages

  resources :notifications do
    collection do
      post :mark_as_read
    end
  end

  resources :haves

  resources :wants

  resources :posts do
    member do
      get :new_layer
      post :create_layer
      post :create_token
      get :all_tokens
      get :show_token
      post :add_rating
      resources :tokens do
        resources :comments do
          get 'add_vote', on: :collection
        end
      end
    end
  end

  root to: 'posts#homepage'

  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  namespace :admin do
    resources :users
  end

  resources :users do
    member do

      resources :items do
        get :items, on: :member
      end
      post :profile_update, to: 'profiles#update'
      get :profile_edit, to: 'profiles#edit'
    end
  end

  # form_for is easier to use with a resourceful route
  resources :contact_forms, only: [:create]
  resources :profiles
  get 'contact' => 'contact_forms#new', as: 'contact'
  post '/users/edit' => 'users/registrations#update'
  # post '/update_user' => 'users/registrations#update'
end

app/views/shared/_nav.html.erb
<div class="navbar navbar navbar-fixed-top mobile-nofixed navbar-light" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
      <span class="sr-only">Toggle navigation</span><span class="icon-bar"></span><span class="icon-bar"></span><span class="icon-bar"></span>
    </button>
  </div>
  <div class="collapse navbar-collapse text-dark bot-nav" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav nav-tag">
      <%= link_to image_tag("logo-icon.jpg", {:style => "width:50px;"}), root_path, class:"nav-link" %>
    </ul>
    <form role="form" action="/posts">
      <ul class="nav navbar-nav text-center nav-search">
        <input type="text" name="term" class="form-control" placeholder="Where do you want to go?">
        <input id="1" class="form-control" type="hidden" name="tags_filter" value="search" />
        <input id="1" class="form-control" type="hidden" name="post_type" value="Problem" />
      </ul>
      <ul class="nav navbar-nav text-center nav-search-btn">
        <button class="dropbtn" type="submit">Go!</button>
      </ul>
    </form>

    <ul class="nav navbar-nav pull-right nav-links">
      <ul class="nav navbar-nav text-center nav-link-box">
        <%= link_to public_feed_path do %>
          <div class="nav-link">
            <%= fa_icon "fab globe 2x" %>
          </div>
        <% end %>
      </ul>
    <% if user_signed_in? %>
      <div class="dropdown icon-box">
        <%= link_to profiles_path do %>
          <div class="nav-link">
            <%= fa_icon "fab bell 2x" %>
          </div>
        <% end %>
        <div class="dropdown-content">
          <% Notification.where(notifiable_type: "Post").where(recipient_id: current_user).where(read_at: nil).each do |t|%>
            <%= link_to t.notifiable_type, post_path(t.notifiable_id) %>
          <% end %>
          <% Notification.where(notifiable_type: "Post").where(recipient_id: current_user).where(read_at: nil).nil? %>
            <%= link_to "Recent Activity", profiles_path %>
        </div>
      </div>

      <div class="dropdown icon-box">
        <%= link_to rooms_path do %>
          <div class="nav-link">
            <%= fa_icon "fab envelope 2x" %>
          </div>
        <% end %>
        <div class="dropdown-content">
          <% Notification.where(notifiable_type: "Message").where(recipient_id: current_user).where(read_at: nil).each do |t|%>
            <%= link_to [t.actor_id, t.notifiable_type].join(" sent a "), room_path(t.room_id) %>
          <% end %>
          <% Notification.where(notifiable_type: "Message").where(recipient_id: current_user).where(read_at: nil).nil? %>
            <%= link_to "All Messages", rooms_path %>
        </div>
      </div>

      <div class="dropdown icon-box-nav">
        <%= fa_icon "fab users 2x" %>
        <div class="dropdown-content">
          <% for friendship in current_user.friendships %>
            <% name = [friendship.friend.first_name, friendship.friend.last_name].compact.join(" ")%>
            <%= link_to name, profile_path(friendship.friend.id) %>
          <% end %>
        </div>
      </div>

      <div class="dropdown icon-box-nav">
        <%= link_to image_tag("timebank.png"), time_banks_path %>
      </div>

      <div class="dropdown icon-box">
        <h4><b> <%= current_user.first_name %> <%= current_user.last_name %></b></h4>
        <div class="dropdown-content">
          <%= link_to "Profile", profile_path(current_user), :class => "b1" %>
          <%= form_for(resource, as: resource_name,
                       url: destroy_user_session_path, html: { method: :delete }) do |f| %>
            <%= f.submit "Log out" %>
          <% end %>
        </div>
      </div>

      <% else %>
      <li class="nav-link-devise">
        <%= link_to 'Sign in', new_user_session_path %>
      </li>
      <li class="nav-link-devise">
        <%= link_to 'Sign up', new_user_registration_path %>
      </li>

      <% end %>
      </ul>
    </li>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<div class="container-flex">
  <div class="row text-center">
    <% if @user.avatar.present? %>
      <%= image_tag(@user.avatar, {:style => "width:175px;", :class => "profile-pic"}) %>
    <% else %>
      <%= image_tag("blank-profile-picture-973460_640.png", {:style => "width:175px;", :class => "profile-pic"}) %>
    <% end %>
  </div>
  <div class="row side-link-box">
    <h3 class="side-links">
      <% if user_signed_in? %>
        <%= link_to "About", profile_path(current_user), :class => "b1" %>
      <% else %>
        <%= link_to "About", root_path, :class => "b1" %>
      <% end %>
    </h3>
    <h3 class="side-links">
      <%= link_to "Feed", profiles_path, :class => "b1" %>
    </h3>

    <h3 class="side-links">
      <%= link_to "Pictures", pic_path(@user.id), :class => "b1" %>
    </h3>
    <h3 class="side-links">
      <%= link_to "Videos", video_path(@user.id), :class => "b1" %>
    </h3>
    <h3 class="side-links">
      <%= link_to "Have", hafe_path(@user.id), :class => "b1" %>
    </h3>
    <h3 class="side-links">
      <%= link_to "Want", want_path(@user.id), :class => "b1" %>
    </h3>
    <h3 class="side-links">
      <%= link_to "Votes", root_path, :class => "b1" %>
    </h3>
    <h3 class="side-links">
      <%= link_to "Notes", profile_posts_path(current_user), :class => "b1" %>
    </h3>
    <h3 class="side-links">
      <%= link_to "Tracking", trackings_path, :class => "b1" %>
    </h3>
  </div>
</div>